apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T06:28:29Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "9746"
  uid: 770991b3-c579-4398-b1d7-97f72154329d
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.105.64.150
  clusterIPs:
  - 10.105.64.150
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32147
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
